version: '3.8'

services:
  test-mongo:
    image: mongo:4.4.1
    container_name: test-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app_container
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://test-mongo:27017/mydatabase
    depends_on:
      - test-mongo

volumes:
  mongo_data:

